[2022-01-29 12:37:35,411] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:35,476] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:35,476] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:35,476] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:35,476] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:35,563] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-05-02 06:00:00+00:00
[2022-01-29 12:37:35,625] {standard_task_runner.py:52} INFO - Started process 4942 to run task
[2022-01-29 12:37:35,722] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '481', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_hmcuj61', '--error-file', '/tmp/tmp047mdgnt']
[2022-01-29 12:37:35,723] {standard_task_runner.py:77} INFO - Job 481: Subtask bigquery_external_table_task
[2022-01-29 12:37:36,245] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-05-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:36,573] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2022-01-29 12:37:36,576] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 12:37:37,527] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210502T060000, start_date=20220129T123735, end_date=20220129T123737
[2022-01-29 12:37:37,629] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:37,720] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:36,108] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:36,127] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:36,127] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:36,127] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:36,127] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:36,148] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-05-02 06:00:00+00:00
[2022-01-29 13:23:36,157] {standard_task_runner.py:52} INFO - Started process 523 to run task
[2022-01-29 13:23:36,168] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '578', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp8al2hyud', '--error-file', '/tmp/tmpe4mz1ziu']
[2022-01-29 13:23:36,170] {standard_task_runner.py:77} INFO - Job 578: Subtask bigquery_external_table_task
[2022-01-29 13:23:36,271] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-05-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:36,461] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:36,502] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2022-01-29 13:23:36,504] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 13:23:36,950] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210502T060000, start_date=20220129T132336, end_date=20220129T132336
[2022-01-29 13:23:37,006] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:37,055] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
