[2022-01-29 11:48:02,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-01-29T11:45:03.704466+00:00 [queued]>
[2022-01-29 11:48:02,463] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-01-29T11:45:03.704466+00:00 [queued]>
[2022-01-29 11:48:02,463] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 11:48:02,463] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-01-29 11:48:02,463] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 11:48:02,477] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-01-29 11:45:03.704466+00:00
[2022-01-29 11:48:02,483] {standard_task_runner.py:52} INFO - Started process 893 to run task
[2022-01-29 11:48:02,490] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2022-01-29T11:45:03.704466+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpvn0s24rb', '--error-file', '/tmp/tmpzx7posy_']
[2022-01-29 11:48:02,491] {standard_task_runner.py:77} INFO - Job 120: Subtask local_to_gcs_task
[2022-01-29 11:48:02,556] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-01-29T11:45:03.704466+00:00 [running]> on host 85e1117cfb12
[2022-01-29 11:48:02,621] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-29T11:45:03.704466+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-29T11:45:03.704466+00:00
[2022-01-29 11:48:03,792] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 11:48:03,804] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20220129T114503, start_date=20220129T114802, end_date=20220129T114803
[2022-01-29 11:48:03,829] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 11:48:03,865] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
