[2022-01-29 12:39:54,165] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-01-02T06:00:00+00:00 [queued]>
[2022-01-29 12:39:54,177] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-01-02T06:00:00+00:00 [queued]>
[2022-01-29 12:39:54,177] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:39:54,177] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-01-29 12:39:54,177] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:39:54,191] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-02 06:00:00+00:00
[2022-01-29 12:39:54,198] {standard_task_runner.py:52} INFO - Started process 5127 to run task
[2022-01-29 12:39:54,205] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2020-01-02T06:00:00+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp1tbsipfw', '--error-file', '/tmp/tmpx2o_0etd']
[2022-01-29 12:39:54,206] {standard_task_runner.py:77} INFO - Job 498: Subtask local_to_gcs_task
[2022-01-29 12:39:54,279] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2020-01-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:39:54,346] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-02T06:00:00+00:00
[2022-01-29 12:39:55,482] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:39:55,496] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20200102T060000, start_date=20220129T123954, end_date=20220129T123955
[2022-01-29 12:39:55,550] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:39:55,590] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
