[2022-01-29 12:37:34,522] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:35,097] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:35,099] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:35,099] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:35,100] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:35,435] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-04-02 06:00:00+00:00
[2022-01-29 12:37:35,481] {standard_task_runner.py:52} INFO - Started process 4940 to run task
[2022-01-29 12:37:35,567] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '479', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpa6hqpn_2', '--error-file', '/tmp/tmpxpqyrrr6']
[2022-01-29 12:37:35,569] {standard_task_runner.py:77} INFO - Job 479: Subtask bigquery_external_table_task
[2022-01-29 12:37:36,462] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:36,824] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2022-01-29 12:37:36,845] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 12:37:37,666] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210402T060000, start_date=20220129T123734, end_date=20220129T123737
[2022-01-29 12:37:37,816] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:37,934] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:36,609] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:36,639] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:36,641] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:36,642] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:36,642] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:36,670] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-04-02 06:00:00+00:00
[2022-01-29 13:23:36,678] {standard_task_runner.py:52} INFO - Started process 524 to run task
[2022-01-29 13:23:36,684] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '579', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpylv9xu3h', '--error-file', '/tmp/tmp9j1_ddzf']
[2022-01-29 13:23:36,686] {standard_task_runner.py:77} INFO - Job 579: Subtask bigquery_external_table_task
[2022-01-29 13:23:36,783] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:36,845] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:36,878] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2022-01-29 13:23:36,880] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 13:23:37,648] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210402T060000, start_date=20220129T132336, end_date=20220129T132337
[2022-01-29 13:23:37,701] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:37,771] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
