[2022-01-29 12:37:59,904] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:59,916] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:59,916] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:59,916] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:59,916] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:59,928] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-12-02 06:00:00+00:00
[2022-01-29 12:37:59,934] {standard_task_runner.py:52} INFO - Started process 5025 to run task
[2022-01-29 12:37:59,941] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-12-02T06:00:00+00:00', '--job-id', '495', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpliby1zla', '--error-file', '/tmp/tmplavz93z7']
[2022-01-29 12:37:59,943] {standard_task_runner.py:77} INFO - Job 495: Subtask bigquery_external_table_task
[2022-01-29 12:38:00,023] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-12-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:38:00,097] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-02T06:00:00+00:00
[2022-01-29 12:38:00,099] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 12:38:00,514] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20211202T060000, start_date=20220129T123759, end_date=20220129T123800
[2022-01-29 12:38:00,555] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:38:00,594] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:27,846] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:27,888] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:27,889] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:27,889] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:27,889] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:27,943] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-12-02 06:00:00+00:00
[2022-01-29 13:23:27,974] {standard_task_runner.py:52} INFO - Started process 494 to run task
[2022-01-29 13:23:27,996] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-12-02T06:00:00+00:00', '--job-id', '571', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpsb4rddhx', '--error-file', '/tmp/tmp8dstmq8n']
[2022-01-29 13:23:27,997] {standard_task_runner.py:77} INFO - Job 571: Subtask bigquery_external_table_task
[2022-01-29 13:23:28,255] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-12-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:28,431] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:28,536] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-02T06:00:00+00:00
[2022-01-29 13:23:28,538] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 13:23:29,128] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20211202T060000, start_date=20220129T132327, end_date=20220129T132329
[2022-01-29 13:23:29,219] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:29,462] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
