[2022-01-29 12:32:18,635] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-01-29T12:32:05.234124+00:00 [queued]>
[2022-01-29 12:32:18,657] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-01-29T12:32:05.234124+00:00 [queued]>
[2022-01-29 12:32:18,658] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:32:18,658] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:32:18,658] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:32:18,683] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-01-29 12:32:05.234124+00:00
[2022-01-29 12:32:18,694] {standard_task_runner.py:52} INFO - Started process 3969 to run task
[2022-01-29 12:32:18,702] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'manual__2022-01-29T12:32:05.234124+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpq21o8alp', '--error-file', '/tmp/tmpny1opg0u']
[2022-01-29 12:32:18,703] {standard_task_runner.py:77} INFO - Job 329: Subtask local_to_gcs_task
[2022-01-29 12:32:18,796] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task manual__2022-01-29T12:32:05.234124+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:32:18,953] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-29T12:32:05.234124+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-29T12:32:05.234124+00:00
[2022-01-29 12:32:20,287] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:32:20,305] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20220129T123205, start_date=20220129T123218, end_date=20220129T123220
[2022-01-29 12:32:20,369] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:32:20,409] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
