[2022-01-29 12:37:34,398] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-07-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:35,207] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-07-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:35,208] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:35,217] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:35,222] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:35,473] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-07-02 06:00:00+00:00
[2022-01-29 12:37:35,517] {standard_task_runner.py:52} INFO - Started process 4941 to run task
[2022-01-29 12:37:35,627] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-07-02T06:00:00+00:00', '--job-id', '478', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpzk0ypxl_', '--error-file', '/tmp/tmpvrcjzm28']
[2022-01-29 12:37:35,629] {standard_task_runner.py:77} INFO - Job 478: Subtask bigquery_external_table_task
[2022-01-29 12:37:36,362] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-07-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:36,669] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-02T06:00:00+00:00
[2022-01-29 12:37:36,671] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 12:37:37,514] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210702T060000, start_date=20220129T123734, end_date=20220129T123737
[2022-01-29 12:37:37,684] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:37,822] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:38,743] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-07-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:38,755] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-07-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:38,756] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:38,756] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:38,756] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:38,768] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-07-02 06:00:00+00:00
[2022-01-29 13:23:38,775] {standard_task_runner.py:52} INFO - Started process 529 to run task
[2022-01-29 13:23:38,782] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-07-02T06:00:00+00:00', '--job-id', '580', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpgmxkqdvr', '--error-file', '/tmp/tmp7_wedwjs']
[2022-01-29 13:23:38,783] {standard_task_runner.py:77} INFO - Job 580: Subtask bigquery_external_table_task
[2022-01-29 13:23:38,884] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-07-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:38,940] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:38,967] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-02T06:00:00+00:00
[2022-01-29 13:23:38,969] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 13:23:39,434] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210702T060000, start_date=20220129T132338, end_date=20220129T132339
[2022-01-29 13:23:39,476] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:39,511] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
