[2022-01-29 12:35:40,054] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-01-29 12:35:40,140] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2022-01-29 12:35:40,140] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:35:40,140] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:35:40,140] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:35:40,200] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-08-02 06:00:00+00:00
[2022-01-29 12:35:40,223] {standard_task_runner.py:52} INFO - Started process 4458 to run task
[2022-01-29 12:35:40,252] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-08-02T06:00:00+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpnig4wdeu', '--error-file', '/tmp/tmpe6sl_6y7']
[2022-01-29 12:35:40,254] {standard_task_runner.py:77} INFO - Job 396: Subtask local_to_gcs_task
[2022-01-29 12:35:40,565] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:35:40,838] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-02T06:00:00+00:00
[2022-01-29 12:35:42,142] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:35:42,288] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20190802T060000, start_date=20220129T123540, end_date=20220129T123542
[2022-01-29 12:35:42,455] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:35:42,677] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
