[2022-01-29 12:37:37,536] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:37,596] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:37,596] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:37,597] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:37,597] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:37,648] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-08-02 06:00:00+00:00
[2022-01-29 12:37:37,688] {standard_task_runner.py:52} INFO - Started process 4953 to run task
[2022-01-29 12:37:37,727] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpwrd7lhop', '--error-file', '/tmp/tmpmhh60tej']
[2022-01-29 12:37:37,753] {standard_task_runner.py:77} INFO - Job 483: Subtask bigquery_external_table_task
[2022-01-29 12:37:37,997] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:38,135] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2022-01-29 12:37:38,138] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 12:37:38,623] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210802T060000, start_date=20220129T123737, end_date=20220129T123738
[2022-01-29 12:37:38,700] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:38,771] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:26,872] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:26,949] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:26,949] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:26,950] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:26,950] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:27,036] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-08-02 06:00:00+00:00
[2022-01-29 13:23:27,068] {standard_task_runner.py:52} INFO - Started process 492 to run task
[2022-01-29 13:23:27,134] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '570', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpzeik7wk5', '--error-file', '/tmp/tmpyatl_i5a']
[2022-01-29 13:23:27,135] {standard_task_runner.py:77} INFO - Job 570: Subtask bigquery_external_table_task
[2022-01-29 13:23:27,801] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-08-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:28,201] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:28,287] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2022-01-29 13:23:28,289] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 13:23:28,821] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20210802T060000, start_date=20220129T132326, end_date=20220129T132328
[2022-01-29 13:23:28,899] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:28,963] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
